# Generated by Django 5.1 on 2024-09-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='estudante',
            new_name='student',
        ),
    ]
