# Generated by Django 5.1 on 2024-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_rename_estudante_registration_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
