# Generated by Django 5.1 on 2024-09-20 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
