# Generated by Django 5.1 on 2024-09-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_alter_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='course_code',
        ),
    ]
