# Generated by Django 5.1 on 2024-09-20 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_alter_student_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
